name: Sync Forks
on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTIONS_PAT }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '29983802+github-actions[bot]@users.noreply.github.com'
        git stash
        git pull
        git stash pop

    - name: Add remote repositories
      run: |

        git remote add frogpilot https://github.com/FrogAi/FrogPilot
        git remote add sunnypilot https://github.com/commaai/openpilot
        git remote add dragonpilot https://github.com/dragonpilot-community/dragonpilot
       

    - name: Fetch and merge FrogPilot
      run: |
        git fetch frogpilot
        git checkout -B FrogPilot frogpilot/FrogPilot
        git push origin FrogPilot --force

    - name: Fetch and merge FrogPilot
      run: |
        git fetch frogpilot
        git checkout -B FrogPilot-69 frogpilot/FrogPilot-69
        git push origin FrogPilot-69 --force

    - name: Fetch and merge commatwo_master
      run: |
        git fetch openpilot
        git checkout -B commatwo_master openpilot/tree/commatwo_master
        git push origin commatwo_master --force
        
    - name: Fetch and merge deprecated-beta2
      run: |
        git fetch dragonpilot
        git checkout -B deprecated-beta2 dragonpilot/tree/deprecated-beta2
        git push origin deprecated-beta2 --force
        
    - name: Fetch and merge d2
      run: |
        git fetch dragonpilot
        git checkout -B d2 dragonpilot/tree/d2
        git push origin d2 --force


    - name: Fetch and merge 0.8.13
      run: |
        git fetch dragonpilot
        git checkout -B 0.8.13 dragonpilot/tree/0.8.13
        git push origin 0.8.13 --force


    
