name: Sync Forks

on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTIONS_PAT }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '29983802+github-actions[bot]@users.noreply.github.com'

    - name: Add remote repositories
      run: |    
        git remote add frogpilot https://github.com/FrogAi/FrogPilot
        git remote add sunnypilot https://github.com/sunnypilot/sunnypilot
        git remote add dragonpilot https://github.com/dragonpilot-community/dragonpilot
               
    - name: Fetch and merge FrogPilot
      run: |
        git fetch frogpilot
        git checkout -B FrogPilot frogpilot/FrogPilot
        git push origin FrogPilot --force
        
    - name: Fetch and merge FrogPilot-69
      run: |
        git fetch frogpilot
        git checkout -B FrogPilot-69 frogpilot/FrogPilot-69
        git push origin FrogPilot-69 --force  
        
    - name: Fetch and merge release-c3
      run: |
        git fetch sunnypilot
        git checkout -B release-c3 sunnypilot/release-c3
        git push origin release-c3 --force
        
    - name: Fetch and merge translation-tests-prebuilt
      run: |
        git fetch sunnypilot
        git checkout -B translation-tests-prebuilt sunnypilot/translation-tests-prebuilt
        git push origin translation-tests-prebuilt --force
        
    - name: Fetch and merge dev-c3
      run: |
        git fetch sunnypilot
        git checkout -B dev-c3 sunnypilot/dev-c3
        git push origin dev-c3 --force

    - name: Fetch and merge d3
      run: |
        git fetch dragonpilot
        git checkout -B d3 dragonpilot/d3
        git push origin d3 --force

